require("user.impatient")

require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.autocommands")

require("user.autopairs")
require("user.bufferline")
require("user.colorscheme")
require("user.Comment")
require("user.dressing")
require("user.git-conflict")
require("user.gitsigns")
require("user.glow")
require("user.hop")
require("user.illuminate")
require("user.indent-blankline")
require("user.lualine")
require("user.luasnip")
require("user.nvim-cmp")
require("user.nvim-notify")
require("user.nvim-surround")
require("user.nvim-tree")
require("user.nvim-treesitter")
require("user.nvim-ts-autotag")
require("user.scope")
require("user.telescope")
require("user.toggleterm")
require("user.vim-bbye")
require("user.vim-maximizer")
require("user.neovim-session-manager")

require("user.lsp")
