require("core.impatient")       -- Keep this plugin always the first
require("core.options")
require("core.keymaps")
require("core.autocommands")
require("core.plugins")
require("core.nvim-notify")     -- Keep this plugin always the last in the "core" group

require("user.colorscheme")
require("user.nvim-tree")
require("user.gitsigns")
require("user.autopairs")
require("user.nvim-surround")
require("user.hop")
require("user.Comment")
require("user.lualine")
require("user.bufferline")
require("user.scope")
require("user.nvim-treesitter")
require("user.nvim-ts-autotag")
require("user.lsp")
require("user.illuminate")
require("user.telescope")
require("user.luasnip")
require("user.cmp")
require("user.indent-blankline")
require("user.toggleterm")
require("user.vim-maximizer")
require("user.vim-bbye")
require("user.git-conflict")
require("user.auto-session")
require("user.glow")
