require("plugins.nvim-tree")
require("plugins.gitsigns")
require("plugins.autopairs")
require("plugins.nvim-surround")
require("plugins.hop")
require("plugins.Comment")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.scope")
require("plugins.nvim-treesitter")
require("plugins.nvim-ts-autotag")
-- require("plugins.lsp")
require("plugins.illuminate")
require("plugins.telescope")
require("plugins.luasnip")
require("plugins.cmp")
require("plugins.indent-blankline")
require("plugins.toggleterm")
require("plugins.vim-maximizer")
require("plugins.vim-bbye")
require("plugins.git-conflict")
require("plugins.glow")

